feat: improve DN core dependencies logic and non-interactive shell logic
- re-implement non-interactive shell logic previously handled
  via BASH_ENV environment variable.
- Removed `dn_bashrc_non_interactive.bash` and migrated its logic to a new
  `.bashrc.dn_non_interactive` for better structure and maintainability.
- Unified `DEBIAN_FRONTEND` pre-condition checks and streamlined debug
  logging across scripts and Dockerfiles for consistency and clarity.
- Replaced redundant comments and legacy TODO sections with actionable
  steps aligning with task NMO-768 requirements.

Issue NMO-768, NMO-770

diff --git a/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom b/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
--- a/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
+++ b/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
@@ -12,13 +12,11 @@ WORKDIR ${DN_DEV_WORKSPACE}
 
 RUN <<EOF
     # Install dependencies
-    {
-      apt-get update && \
-      apt-get upgrade --assume-yes
-    } || exit 1
+    apt-get update
+    apt-get upgrade --assume-yes
 
     apt-get install --assume-yes --no-install-recommends \
-        ros-${ROS_DISTRO}-rosbridge-msgs \
+        ros-${ROS_DISTRO:?err}-rosbridge-msgs \
         python3-tornado \
         python3-bson \
         python3-pymongo \
@@ -54,6 +52,7 @@ RUN <<EOF
         ros-${ROS_DISTRO}-urg-node-msgs \
         || exit 1
 
+    # ....Teardown.................................................................................
     apt-get autoremove --assume-yes
     apt-get clean
     rm -rf /var/lib/apt/lists/*
@@ -69,13 +68,13 @@ RUN <<EOF
 
     apt-get update || exit 1
 
-    rosdep update --rosdistro ${ROS_DISTRO} || exit 1
+    rosdep update --rosdistro ${ROS_DISTRO:?err} || exit 1
     rosdep fix-permissions
 
     rosdep install \
         --ignore-packages-from-source \
-        --from-path ./src  \
-        --rosdistro ${ROS_DISTRO}  \
+        --from-path ./src \
+        --rosdistro ${ROS_DISTRO} \
         -y \
         || exit 1
 
@@ -96,70 +95,11 @@ RUN <<EOF
           "--event-handlers" "console_direct+"
        )
     echo -e "COLCON_FLAGS=( ${COLCON_FLAGS[*]} )"
+
+    dn::source_ros2 || exit 1
     colcon build ${COLCON_FLAGS[@]} || exit 1
 
-    # ===ROS sourcing logic for interactive and non-interactive shell==============================
-    # (since .bashrc is not executed in non-interactive shell)
-
-    # Note:
-    #  - Environment variable formated such as "\$``{ENV_VAR}``" wont be substituted at build time.
-    (
-        echo ""
-        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
-        echo "# Source ROS2 environment"
-        echo "echo -e \"\\033[1;2m\" # MSG_DIMMED_FORMAT"
-        echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""
-        echo "source /opt/ros/${ROS_DISTRO}/setup.bash"
-        echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"
-        echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""
-        echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"
-        echo "fi"
-        echo "echo -e \"\\033[0m\" # MSG_END_FORMAT"
-        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
-        echo ""
-    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
-
-    (
-        echo ""
-        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
-        echo "# Source ROS2 environment"
-        echo "echo -e \"\\033[1;2m\" # MSG_DIMMED_FORMAT"
-        echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash\""
-        echo "source /opt/ros/${ROS_DISTRO}/setup.bash"
-        echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"
-        echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash\""
-        echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"
-        echo "fi"
-        echo "echo -e \"\\033[0m\" # MSG_END_FORMAT"
-        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
-        echo ""
-    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash
-
-    # (NICE TO HAVE) ToDo: DN_CONTAINER_NAME is being set with the build arg instead of the env at runtime
-    #      echo ""
-    #      echo "# Dockerized-NorLab › Quickhack for connecting to pycharm-debugger (over ssh)"
-    #      echo "export DN_CONTAINER_NAME=$DN_CONTAINER_NAME"
-    #      echo "export DN_ACTIVATE_POWERLINE_PROMT=$DN_ACTIVATE_POWERLINE_PROMT"
-
-    echo "Add ROS2 specific aliases"
-    (
-        echo ""
-        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
-        echo "alias dn_source_ros_worspace_overlay='echo \"Sourcing ${DN_DEV_WORKSPACE} overlay \" && source ${DN_DEV_WORKSPACE}/install/local_setup.bash'"
-        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
-        echo ""
-    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
-
-    echo "Add ROS2 specific config to /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash"
-    (
-        echo ""
-        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
-        echo "# Enable ROS2 log collouring"
-        echo "export RCUTILS_COLORIZED_OUTPUT=1"
-        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
-        echo ""
-    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
-
+    # ....Teardown.................................................................................
     apt-get autoremove --assume-yes
     apt-get clean
     rm -rf /var/lib/apt/lists/*
@@ -168,10 +108,17 @@ EOF
 
 FROM ros2-custom-install AS test
 
-
-# Note: ROS2 distro should be sourced automaticaly via our dn_bashrc_non_interactive.bash setup
+# Note: ROS2 distro should be sourced automaticaly via our .bashrc.dn_non_interactive setup
 RUN <<EOF
-    echo "(ROS2 sourcing) Non-interactive shell sanity check. Validate dn_bashrc_non_interactive.bash logic"
+    echo "(ROS2 sourcing) Non-interactive shell sanity check. Validate .bashrc.dn_non_interactive logic..."
+
+    echo -e "\nLog .bashrc.dn_non_interactive state\n"
+    cat /dockerized-norlab/dockerized-norlab-images/container-tools/bash_run_config/.bashrc.dn_non_interactive
+
+    test -n "$( declare -f dn::source_ros2 )" || { echo -e "${_dna_error_prefix} The DN lib is not loaded!" 1>&2 && exit 1; }
+    dn::source_ros2 || exit 1
+
+    echo -e "\nPre-condition check...\n"
     {
         test -n ${ROS_VERSION:?'Build argument needs to be set and non-empty.'} && \
         test -n ${ROS_PYTHON_VERSION:?'Build argument needs to be set and non-empty.'} && \
@@ -182,23 +129,25 @@ RUN <<EOF
     } || exit 1
     #    test -n ${CMAKE_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
 
+    echo -e "\nCheck ros2 is available...\n"
     {
         python -c "import rclpy" && \
         ros2 pkg list ;
     } || exit 1
-
-    echo -e "\nLog dn_bashrc.bash content\n"
-    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
-
-    echo -e "\nLog dn_bashrc_non_interactive.bash content\n"
-    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash
-
 EOF
 
-# Note: ROS2 distro should be sourced automaticaly via our dn_bashrc_non_interactive.bash setup
+# Note: ROS2 distro should be sourced automaticaly via our .bashrc.dn_non_interactive setup
 SHELL ["/bin/bash", "-i", "-c"]
 RUN <<EOF
-    echo "(ROS2 sourcing) Interactive shell sanity check. Validate dn_bashrc.bash logic"
+    echo "(ROS2 sourcing) Interactive shell sanity check. Validate .bashrc.dn logic..."
+
+    echo -e "\nLog .bashrc.dn state\n"
+    cat /dockerized-norlab/dockerized-norlab-images/container-tools/bash_run_config/.bashrc.dn
+
+    test -n "$( declare -f dn::source_ros2 )" || { echo -e "${_dna_error_prefix} The DN lib is not loaded!" 1>&2 && exit 1; }
+    dn::source_ros2 || exit 1
+
+    echo -e "\nPre-condition check...\n"
     {
         test -n ${ROS_VERSION:?'Build argument needs to be set and non-empty.'} && \
         test -n ${ROS_PYTHON_VERSION:?'Build argument needs to be set and non-empty.'} && \
@@ -209,6 +158,7 @@ RUN <<EOF
     } || exit 1
         #    test -n ${CMAKE_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
 
+    echo -e "\nCheck ros2 is available...\n"
     {
         python -c "import rclpy" && \
         ros2 pkg list ;
@@ -217,18 +167,6 @@ EOF
 
 
 FROM ros2-custom-install AS final
-
-
-# ....TMP DEV introspection........................................................................
-## (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
-#RUN <<EOF
-#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash
-#    echo
-#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
-#    exit 1
-#EOF
-#RUN echo "${0}:not implemented error" && exit 1
-# ........................................................................TMP DEV introspection....
 
 
 
diff --git a/dockerized-norlab-images/core-images/dn-project/project-deploy/Dockerfile b/dockerized-norlab-images/core-images/dn-project/project-deploy/Dockerfile
--- a/dockerized-norlab-images/core-images/dn-project/project-deploy/Dockerfile
+++ b/dockerized-norlab-images/core-images/dn-project/project-deploy/Dockerfile
@@ -27,7 +27,7 @@ RUN <<EOF
         test -n ${DN_PROJECT_GIT_DOMAIN:?'Env variable need to be set and non-empty.'} && \
         test -n ${DN_PROJECT_DEPLOY_REPO_BRANCH:?'Env variable need to be set and non-empty.'} && \
         test -n "${DEBIAN_FRONTEND:?'Env variable need to be set and non-empty.'}" && \
-        { [[ "${DEBIAN_FRONTEND}" == "noninteractive" ]] || n2st::print_msg_error "DEBIAN_FRONTEND == ${DEBIAN_FRONTEND} != noninteractive" ; } ;
+        [[ "${DEBIAN_FRONTEND}" == "noninteractive" ]];
     } || n2st::print_msg_error_and_exit "Failed pre-condition checks!"
 EOF
 
@@ -158,14 +158,18 @@ RUN <<EOF
     )
     n2st::print_msg "COLCON_FLAGS=("${COLCON_FLAGS[*]}")"
 
-    source "/opt/ros/${ROS_DISTRO}/setup.bash"
-    if [[ -d "${DN_DEV_WORKSPACE}/install/setup.bash" ]]; then
-      source "${DN_DEV_WORKSPACE}/install/setup.bash"
-    fi
+    # (CRITICAL) ToDo: should replace the following bloc with dn::source_ros2 (ref task NMO-770)
+    #source "/opt/ros/${ROS_DISTRO}/setup.bash"
+    #if [[ -d "${DN_DEV_WORKSPACE}/install/setup.bash" ]]; then
+    #  source "${DN_DEV_WORKSPACE}/install/setup.bash"
+    #fi
+    test -n "$( declare -f dn::source_ros2 )" || { echo -e "${_dna_error_prefix} The DN lib is not loaded!" 1>&2 && exit 1; }
+    dn::source_ros2 || exit 1
 
     n2st::print_msg "Execute colcon build..."
     colcon build ${COLCON_FLAGS[@]} || n2st::print_msg_error_and_exit "Failed colcon build!"
 
+    # ....Teardown.................................................................................
     apt-get autoremove --assume-yes
     apt-get clean
     rm -rf /var/lib/apt/lists/*
@@ -201,7 +205,7 @@ RUN <<EOF
       chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_PROJECT_PATH:?err}
       chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_DEV_WORKSPACE:?err}
     } || {
-      # Collect debugg information on faillure
+      # Collect debug information on faillure
       pwd
       tree -agu
       tree -agu ${DN_PROJECT_USER_HOME}
@@ -214,35 +218,27 @@ RUN <<EOF
       echo ""
       echo "# >>> dockerized-norlab project-deploy"
       echo "# Dockerized-NorLab aliases (from project-deploy img)"
-      echo "alias dn_info='source /dockerized-norlab/dockerized-norlab-images/container-tools/dn_info.bash'"
+      echo "alias dn-info='source /dockerized-norlab/dockerized-norlab-images/container-tools/dn_info.bash'"
       echo "# <<< dockerized-norlab project-deploy"
       echo ""
     ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
 EOF
-
-# ....TMP DEV introspection........................................................................
-## (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
-#RUN <<EOF
-#    # TMP DEV introspection
-#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
-#    echo -e "\n${0}: not implemented error\n" && exit 1
-#EOF
-# ........................................................................TMP DEV introspection....
-
-# ....TMP DEV dn_info.bash refactor................................................................
-### (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
-#WORKDIR /dockerized-norlab/dockerized-norlab-images/container-tools
-#COPY --from=context-dn-container-tools ./dn_info.bash .
-# ................................................................TMP DEV dn_info.bash refactor....
 
 
 FROM package-project-src-code AS test
 
 # ....Test project user............................................................................
 USER ${DN_PROJECT_USER:?'Env variable needs to be set and non-empty.'}
-SHELL ["/bin/bash", "-c"]
+#SHELL ["/bin/bash", "-c"]
+SHELL ["/usr/local/bin/bash-dn-buildtime", "-c"]
 
 RUN <<EOF
+    echo -e "\nSanity check...\n"
+    cat ~/.bashrc
+    echo
+    test -n "$( declare -f dn::source_ros2 )" || { echo -e "${_dna_error_prefix} The DN lib is not loaded!" 1>&2 && exit 1; }
+    dn::source_ros2 || exit 1
+
     {
         test "$(whoami)" == "${DN_PROJECT_USER}" && \
         test -d "/home/${DN_PROJECT_USER}" ;
