refactor: use here-doc for multi-line RUN instructions in Dockerfiles
- Consolidate multi-line RUN instructions using here-doc syntax for
  better readability.
- Adjust environment variable assignments for consistency.
- Update comments and refactor ToDo notes for clarity.
- Ensure debugging information and testing steps are incorporated correctly.

Issue RLRP-213, NMO-548, NMO-540

diff --git a/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom b/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
--- a/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
+++ b/dockerized-norlab-images/core-images/dependencies/Dockerfile.ros2-dn-custom
@@ -14,39 +14,45 @@ ENV TERM=${TERM:-"xterm-256color"}
 
 # ====Begin install================================================================================
 
-RUN pip3 install --no-cache-dir  \
-        transforms3d \
-    && echo \
-    && apt-get update \
-    && apt-get update --fix-missing  \
-    && apt-get upgrade -y \
-    && echo "Quickhack: reinstall 'robot-state-publisher' to solved the 'process has died' error" \
-    && apt-get install -y \
-            ros-${ROS_DISTRO}-robot-state-publisher \
-    && apt-get install -y \
-            ros-${ROS_DISTRO}-rviz2 \
-            ros-${ROS_DISTRO}-rviz-visual-tools \
-            ros-${ROS_DISTRO}-nav2-rviz-plugins \
-            ros-${ROS_DISTRO}-rqt-graph \
-            libqt5svg5 \
-    && apt-get autoremove -y \
-    && apt-get clean
+RUN <<EOF
+    pip3 install --no-cache-dir  \
+        transforms3d
+
+    apt-get update
+    apt-get update --fix-missing
+    apt-get upgrade -y
+
+    # Quickhack: reinstall 'robot-state-publisher' to solved the 'process has died' error"
+    apt-get install -y ros-${ROS_DISTRO}-robot-state-publisher
+
+    apt-get install -y \
+      ros-${ROS_DISTRO}-rviz2 \
+      ros-${ROS_DISTRO}-rviz-visual-tools \
+      ros-${ROS_DISTRO}-nav2-rviz-plugins \
+      ros-${ROS_DISTRO}-rqt-graph \
+      libqt5svg5
+
+    apt-get autoremove -y
+    apt-get clean
+EOF
 
 # ....install ROS2 specific utilities..............................................................
-RUN pip3 install --no-cache-dir \
-      osrf-pycommon \
-      rosbags \
-      rosbags-dataframe \
-      rosbag-tools[plot] \
-    && echo \
-    && apt-get update --fix-missing \
-    && apt-get install --assume-yes \
-            ros-${ROS_DISTRO:?err}-ackermann-msgs \
-            ros-${ROS_DISTRO}-vesc-msgs \
-            ros-${ROS_DISTRO}-rosbridge-msgs \
-            ros-${ROS_DISTRO}-urg-node-msgs \
-    && apt-get clean \
-    && rm -rf /var/lib/apt/lists/*
+RUN <<EOF
+    pip3 install --no-cache-dir \
+          osrf-pycommon \
+          rosbags \
+          rosbags-dataframe \
+          rosbag-tools[plot]
+
+    apt-get update --fix-missing
+    apt-get install --assume-yes \
+        ros-${ROS_DISTRO:?err}-ackermann-msgs \
+        ros-${ROS_DISTRO}-vesc-msgs \
+        ros-${ROS_DISTRO}-rosbridge-msgs \
+        ros-${ROS_DISTRO}-urg-node-msgs
+    apt-get clean
+    rm -rf /var/lib/apt/lists/*
+EOF
 
 # # https://pypi.org/project/ros2-numpy/
 # # https://github.com/Box-Robotics/ros2_numpy
@@ -69,108 +75,75 @@ WORKDIR ${DN_DEV_WORKSPACE}
 
 ARG TARGETPLATFORM
 ARG BUILDPLATFORM
-RUN echo "sourcing /opt/ros/${ROS_DISTRO}/setup.bash" \
-    && source /opt/ros/${ROS_DISTRO}/setup.bash \
-    && echo "sourcing ${DN_DEV_WORKSPACE}/install/setup.bash" \
-    && source ${DN_DEV_WORKSPACE}/install/setup.bash \
-    && apt-get update --fix-missing \
-    && rosdep update --rosdistro ${ROS_DISTRO} --include-eol-distros \
-    && rosdep fix-permissions \
-    && rosdep install  \
-            --ignore-packages-from-source \
-            --from-path ./src  \
-            --rosdistro ${ROS_DISTRO}  \
-            -y \
-    && colcon version-check \
-    && COLCON_FLAGS=() \
-    && if [[ ${TARGETPLATFORM:?err} != ${BUILDPLATFORM:?err} ]]; then \
-         echo -e "Builder is running in architecture virtualisation" \
-         && COLCON_FLAGS+=(--executor sequential) ; \
-      else \
-         echo -e "Builder is running on native architecture" \
-         && COLCON_FLAGS+=(--symlink-install) ; \
-      fi \
-    && COLCON_FLAGS+=( \
-          --cmake-clean-cache \
-          --cmake-args -DCMAKE_BUILD_TYPE=Release \
-          --event-handlers console_direct+ \
-       ) \
-    && echo -e "COLCON_FLAGS=("${COLCON_FLAGS[*]}")" \
-    && colcon build ${COLCON_FLAGS[@]}
+RUN <<EOF
+#    echo "sourcing /opt/ros/${ROS_DISTRO}/setup.bash"
+#    source /opt/ros/${ROS_DISTRO}/setup.bash
+#    echo "sourcing ${DN_DEV_WORKSPACE}/install/setup.bash"
+#    source ${DN_DEV_WORKSPACE}/install/setup.bash
 
-# ===Execute ros sourcing system wide instead of in .bashrc========================================
+    apt-get update --fix-missing
+    rosdep update --rosdistro ${ROS_DISTRO} --include-eol-distros
+    rosdep fix-permissions
+    rosdep install \
+        --ignore-packages-from-source \
+        --from-path ./src  \
+        --rosdistro ${ROS_DISTRO}  \
+        -y
+
+    colcon version-check
+
+    COLCON_FLAGS=()
+    if [[ ${TARGETPLATFORM:?err} != ${BUILDPLATFORM:?err} ]]; then
+      echo -e "Builder is running in architecture virtualisation"
+      COLCON_FLAGS+=( "--executor" "sequential" )
+    else
+      echo -e "Builder is running on native architecture"
+      COLCON_FLAGS+=( "--symlink-install" )
+    fi
+
+    COLCON_FLAGS+=(
+          "--cmake-clean-cache"
+          "--cmake-args" "-DCMAKE_BUILD_TYPE=Release"
+          "--event-handlers" "console_direct+"
+       )
+    echo -e "COLCON_FLAGS=( ${COLCON_FLAGS[*]} )"
+    colcon build ${COLCON_FLAGS[@]}
+EOF
+
+# ===ROS sourcing logic for interactive and non-interactive shell==================================
 # (since .bashrc is not executed in non-interactive shell)
 
-## (NICE TO HAVE) ToDo: on task end >> delete next bloc ↓↓ (ref tsk NMO-540)
-#RUN touch /etc/profile.d/02-dn-source-ros-system-wide.sh \
-#    && chmod +x /etc/profile.d/02-dn-source-ros-system-wide.sh \
-#    && ( \
-#      echo ""; \
-#      echo "# Dockerized-NorLab › Execute ros sourcing system wide instead of in .bashrc "; \
-#      echo "#   which is not executed in non-interactive shell such as in pycharm-debugger"; \
-#      echo "echo \"sourcing /opt/ros/\$``{ROS_DISTRO}``/setup.bash from /etc/profile.d/\""; \
-#      echo "source /opt/ros/\$``{ROS_DISTRO}``/setup.bash"; \
-#      echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"; \
-#      echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /etc/profile.d/\""; \
-#      echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"; \
-#      echo "fi"; \
-#      echo ""; \
-#    ) > /etc/profile.d/02-dn-source-ros-system-wide.sh \
-#    && echo "" \
-#    && ( \
-#      echo ""; \
-#      echo "# Dockerized-NorLab › Source ROS2 environment"; \
-#      echo "echo \"sourcing /opt/ros/\$``{ROS_DISTRO}``/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""; \
-#      echo "source /opt/ros/\$``{ROS_DISTRO}``/setup.bash";  \
-#      echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"; \
-#      echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""; \
-#      echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"; \
-#      echo "fi"; \
-#      echo ""; \
-#    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
-
-# (Priority) ToDo: assess command '"source /dockerized-norlab/project/project-develop/dn_expose_container_env_variables.bash"' (ref task NMO-540)
-RUN touch /etc/profile.d/02-dn-source-ros-system-wide.sh \
-    && chmod +x /etc/profile.d/02-dn-source-ros-system-wide.sh \
-    && ( \
-      echo ""; \
-      echo "#DN_EXPOSED_ENV_PATH=/dn_container_env_variable/.env.dn_expose_\$``{DN_CONTAINER_NAME}``"; \
-      echo "#if [[ -f \$``{DN_EXPOSED_ENV_PATH}`` ]]; then"; \
-      echo "#  echo \"sourcing \$``{DN_EXPOSED_ENV_PATH}``\""; \
-      echo "#  set -o allexport"; \
-      echo "#  source \$``{DN_EXPOSED_ENV_PATH}``"; \
-      echo "#  set +o allexport"; \
-      echo "#else"; \
-      echo "#  # Intermediate step prior to the dn-project services building stage"; \
-      echo "#  export ROS_DISTRO=${ROS_DISTRO}"; \
-      echo "#  export DN_DEV_WORKSPACE=${DN_DEV_WORKSPACE}"; \
-      echo "#fi"; \
-      echo ""; \
-      echo "# Dockerized-NorLab › Execute ros sourcing system wide instead of in .bashrc "; \
-      echo "#   which is not executed in non-interactive shell such as in pycharm-debugger"; \
-      echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /etc/profile.d/\""; \
-      echo "source /opt/ros/${ROS_DISTRO}/setup.bash"; \
-      echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"; \
-      echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /etc/profile.d/\""; \
-      echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"; \
-      echo "fi"; \
-      echo ""; \
-    ) > /etc/profile.d/02-dn-source-ros-system-wide.sh \
-    && echo "" \
-    && ( \
-      echo ""; \
-      echo "# Dockerized-NorLab › Source ROS2 environment"; \
-      echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""; \
-      echo "source /opt/ros/${ROS_DISTRO}/setup.bash";  \
-      echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"; \
-      echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""; \
-      echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"; \
-      echo "fi"; \
-      echo ""; \
+# Note:
+#  - Environment variable formated such as "\$``{ENV_VAR}``" wont be substituted at build time.
+RUN <<EOF
+    (
+        echo ""
+        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
+        echo "# Source ROS2 environment"
+        echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""
+        echo "source /opt/ros/${ROS_DISTRO}/setup.bash"
+        echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"
+        echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash\""
+        echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"
+        echo "fi"
+        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
+        echo ""
     ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
 
-# To source ros in non-interactive & non-login shell
-ENV BASH_ENV=/etc/profile.d/02-dn-source-ros-system-wide.sh
+    (
+        echo ""
+        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
+        echo "# Source ROS2 environment"
+        echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash\""
+        echo "source /opt/ros/${ROS_DISTRO}/setup.bash"
+        echo "if [[ -f \$``{DN_DEV_WORKSPACE}``/install/setup.bash ]]; then"
+        echo "  echo \"sourcing \$``{DN_DEV_WORKSPACE}``/install/setup.bash from /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash\""
+        echo "  source \$``{DN_DEV_WORKSPACE}``/install/setup.bash"
+        echo "fi"
+        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
+        echo ""
+    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash
+EOF
 
 # (NICE TO HAVE) ToDo: DN_CONTAINER_NAME is being set with the build arg instead of the env at runtime
 #      echo ""; \
@@ -178,36 +151,83 @@ ENV BASH_ENV=/etc/profile.d/02-dn-source-ros-system-wide.sh
 #      echo "export DN_CONTAINER_NAME=$DN_CONTAINER_NAME"; \
 #      echo "export DN_ACTIVATE_POWERLINE_PROMT=$DN_ACTIVATE_POWERLINE_PROMT"; \
 
-RUN echo "Add ROS2 specific aliases" && \
-    ( \
-      echo "alias dn_source_ros_worspace_overlay='echo \"Sourcing ${DN_DEV_WORKSPACE} overlay \" && source ${DN_DEV_WORKSPACE}/install/local_setup.bash'"; \
-    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash && \
-    echo "Add ROS2 specific config to /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash" && \
-    ( \
-      echo ""; \
-      echo "# Enable ROS2 log collouring"; \
-      echo "export RCUTILS_COLORIZED_OUTPUT=1"; \
-      echo ""; \
+RUN <<EOF
+    echo "Add ROS2 specific aliases"
+    (
+        echo ""
+        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
+        echo "alias dn_source_ros_worspace_overlay='echo \"Sourcing ${DN_DEV_WORKSPACE} overlay \" && source ${DN_DEV_WORKSPACE}/install/local_setup.bash'"
+        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
+        echo ""
+    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
+
+    echo "Add ROS2 specific config to /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash"
+    (
+        echo ""
+        echo "# >>> dockerized-norlab dependencies ros2-dn-custom"
+        echo "# Enable ROS2 log collouring"
+        echo "export RCUTILS_COLORIZED_OUTPUT=1"
+        echo "# <<< dockerized-norlab dependencies ros2-dn-custom"
+        echo ""
     ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
+EOF
 
 
 FROM ros2-custom-install AS test
 
-# Note: ROS2 distro should be sourced automaticaly via our /etc/profile.d setup
-RUN echo "Sanity check" \
-    && echo ROS_VERSION=${ROS_VERSION:?'Build argument needs to be set and non-empty.'} \
-    && echo ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION:?'Build argument needs to be set and non-empty.'} \
-    && echo ROS_DISTRO=${ROS_DISTRO:?'Build argument needs to be set and non-empty.'} \
-    && echo AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} \
-#    && echo CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} \
-    && echo COLCON_PREFIX_PATH=${COLCON_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} \
-    && echo PYTHONPATH=${PYTHONPATH:?'Build argument needs to be set and non-empty.'} \
-    && python -c "import rclpy" \
-    && ros2 pkg list
+# Note: ROS2 distro should be sourced automaticaly via our dn_bashrc_non_interactive.bash setup
+RUN <<EOF
+    echo "(ROS2 sourcing) Non-interactive shell sanity check. Validate dn_bashrc_non_interactive.bash logic"
+    {
+        test -n ${ROS_VERSION:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${ROS_PYTHON_VERSION:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${ROS_DISTRO:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+    #    test -n ${CMAKE_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${COLCON_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${PYTHONPATH:?'Build argument needs to be set and non-empty.'} ;
+    } || exit 1
+
+    {
+        python -c "import rclpy" && \
+        ros2 pkg list ;
+    } || exit 1
+EOF
+
+# Note: ROS2 distro should be sourced automaticaly via our dn_bashrc_non_interactive.bash setup
+SHELL ["/bin/bash", "-i", "-c"]
+RUN <<EOF
+    echo "(ROS2 sourcing) Interactive shell sanity check. Validate dn_bashrc.bash logic"
+    {
+        test -n ${ROS_VERSION:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${ROS_PYTHON_VERSION:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${ROS_DISTRO:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+        #    test -n ${CMAKE_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${COLCON_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} && \
+        test -n ${PYTHONPATH:?'Build argument needs to be set and non-empty.'} ;
+    } || exit 1
+
+    {
+        python -c "import rclpy" && \
+        ros2 pkg list ;
+    } || exit 1
+EOF
 
 
 FROM ros2-custom-install AS final
 WORKDIR ${DN_DEV_WORKSPACE}
+
+# ....TMP DEV introspection........................................................................
+## (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
+#RUN <<EOF
+#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc_non_interactive.bash
+#    echo
+#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash
+#    exit 1
+#EOF
+#RUN echo "${0}:not implemented error" && exit 1
+# ........................................................................TMP DEV introspection....
 
 CMD [ "bash" ]
 
diff --git a/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile b/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
--- a/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
+++ b/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
@@ -6,25 +6,35 @@ FROM ${BASE_IMAGE:?err}:${BASE_IMAGE_TAG:?err} AS debugging-tools
 ARG IS_TEAMCITY_RUN
 ENV IS_TEAMCITY_RUN=${IS_TEAMCITY_RUN:-false}
 
-RUN echo "Pre-condition checks" && { \
-    test $(whoami) == "root" &&  \
-    test -n ${DN_PROJECT_USER:?'Env variable need to be set and non-empty.'} && \
-    test -n ${DN_PROJECT_USER_HOME:?'Env variable need to be set and non-empty.'} && \
-    test -d ${DN_PROJECT_USER_HOME} && \
-    test -n ${DN_PROJECT_PATH:?'Env variable need to be set and non-empty.'} && \
-    test -d ${DN_PROJECT_PATH} ; \
+ENV DN_PROJECT_SERVICE=project-develop
+ENV DN_PROJECT_SERVICE_DIR=/dockerized-norlab/project/${DN_PROJECT_SERVICE}
+
+RUN <<EOF
+    echo "Pre-condition checks"
+    {
+        test $(whoami) == "root" &&  \
+        test -n ${DN_PROJECT_USER:?'Env variable need to be set and non-empty.'} && \
+        test -n ${DN_PROJECT_USER_HOME:?'Env variable need to be set and non-empty.'} && \
+        test -d ${DN_PROJECT_USER_HOME} && \
+        test -n ${DN_PROJECT_PATH:?'Env variable need to be set and non-empty.'} && \
+        test -d ${DN_PROJECT_PATH} ;
     } || exit 1
+EOF
 
 # Set python to print stdin/sderr in real-time for dev/debug
 ENV PYTHONUNBUFFERED=1
 
 # ....ssh and gdb server config....................................................................
+# Note: Set ENV default at build time via ARG in the dockerfile
+ARG DN_SSH_SERVER_PORT=2222
+ARG DN_GDB_SERVER_PORT=7777
+
 # ssh port, remaped from default 22 to 2222
-ENV DN_SSH_SERVER_PORT=${DN_SSH_SERVER_PORT:-2222}
+ENV DN_SSH_SERVER_PORT=${DN_SSH_SERVER_PORT}
 EXPOSE ${DN_SSH_SERVER_PORT}
 
 # gdbserver port, remaped from default 77 to 7777
-ENV DN_GDB_SERVER_PORT=${DN_GDB_SERVER_PORT:-7777}
+ENV DN_GDB_SERVER_PORT=${DN_GDB_SERVER_PORT}
 EXPOSE ${DN_GDB_SERVER_PORT}
 
 # ...debugging user config.........................................................................
@@ -34,19 +44,14 @@ ARG DN_SSH_SERVER_USER_PASSWORD=lasagne
 
 # ....install debugging tools......................................................................
 WORKDIR /dockerized-norlab/dockerized-norlab-images/container-tools
-
 COPY --from=context-dn-container-tools ./dn_install_debugging_tools.bash .
 RUN source ./dn_install_debugging_tools.bash \
     && rm -f ./dn_install_debugging_tools.bash \
     && test -f /etc/ssh/sshd_config_dockerized_norlab_openssh_server || exit 1
 
-## Create the pycharm-debugger user directory
-#WORKDIR /home/${DN_SSH_SERVER_USER}/tmp/${DN_PROJECT_GIT_NAME:?err}
-#RUN chown -R ${DN_SSH_SERVER_USER} /home/${DN_SSH_SERVER_USER}/tmp/${DN_PROJECT_GIT_NAME}/
-
 
 # ====Project specific ros setup===================================================================
-FROM debugging-tools AS project-specific-ros-setup
+FROM debugging-tools AS dockerized-norlab-project-internal
 
 # ....DN and DN-project entrypoints and utilities................................................
 
@@ -58,7 +63,6 @@ FROM debugging-tools AS project-specific-ros-setup
 # all dn-project service (ref task NMO-558)
 
 # Note: Its easier and more robust to copy DN files to root and then symlink them in project user.
-ENV DN_PROJECT_SERVICE_DIR=/dockerized-norlab/project/project-develop
 WORKDIR ${DN_PROJECT_SERVICE_DIR}
 COPY dn_entrypoint.init.bash dn_entrypoint.attach.bash dn_ros2_rebuild_dev_workspace.bash dn_fetch_ros_env_variables.bash dn_expose_container_env_variables.bash ./
 
@@ -71,118 +75,166 @@ RUN chmod +x dn_entrypoint.init.bash && \
 # Create required directories
 WORKDIR /dn_container_env_variable/
 
-# Create soft link in the home dir
-RUN ln -s /dn_container_env_variable ${DN_PROJECT_USER_HOME}/dn_container_env_variable \
-    && ln -s ${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.init.bash ${DN_PROJECT_USER_HOME}/dn_entrypoint.init.bash \
-    && ln -s ${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.attach.bash ${DN_PROJECT_USER_HOME}/dn_entrypoint.attach.bash \
-    && ln -s ${DN_PROJECT_SERVICE_DIR}/dn_ros2_rebuild_dev_workspace.bash ${DN_PROJECT_USER_HOME}/dn_ros2_rebuild_dev_workspace.bash \
-    && ln -s ${DN_PROJECT_SERVICE_DIR}/dn_fetch_ros_env_variables.bash ${DN_PROJECT_USER_HOME}/dn_fetch_ros_env_variables.bash \
-    && ln -s ${DN_PROJECT_SERVICE_DIR}/dn_expose_container_env_variables.bash ${DN_PROJECT_USER_HOME}/dn_expose_container_env_variables.bash
-
-# ....Project directories ownership and simlink....................................................
-
-# (CRITICAL) ToDo: validate user have permission to execute file in that dir (ref task NMO-548)
 RUN <<EOF
-{
-  chown -R $(id -u ${DN_PROJECT_USER:?err}):$(id -g ${DN_PROJECT_USER}) ${DN_PROJECT_USER_HOME:?err}
-  chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_PROJECT_PATH:?err}
-  chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_DEV_WORKSPACE:?err}
-} || {
-  pwd
-  tree -agu
-  tree -agu ${DN_PROJECT_USER_HOME}
-  tree -agu ${DN_DEV_WORKSPACE}
-  exit 1
-}
+    # Create soft link in the home dir
+    ln -s /dn_container_env_variable ${DN_PROJECT_USER_HOME}/dn_container_env_variable
+    ln -s ${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.init.bash ${DN_PROJECT_USER_HOME}/dn_entrypoint.init.bash
+    ln -s ${DN_PROJECT_SERVICE_DIR}/dn_entrypoint.attach.bash ${DN_PROJECT_USER_HOME}/dn_entrypoint.attach.bash
+    ln -s ${DN_PROJECT_SERVICE_DIR}/dn_ros2_rebuild_dev_workspace.bash ${DN_PROJECT_USER_HOME}/dn_ros2_rebuild_dev_workspace.bash
+    ln -s ${DN_PROJECT_SERVICE_DIR}/dn_fetch_ros_env_variables.bash ${DN_PROJECT_USER_HOME}/dn_fetch_ros_env_variables.bash
+    ln -s ${DN_PROJECT_SERVICE_DIR}/dn_expose_container_env_variables.bash ${DN_PROJECT_USER_HOME}/dn_expose_container_env_variables.bash
+
+
+    # ....Project directories ownership and simlink....................................................
+    # (CRITICAL) ToDo: validate user have permission to execute file in that dir (ref task NMO-548)
+    {
+      chown -R $(id -u ${DN_PROJECT_USER:?err}):$(id -g ${DN_PROJECT_USER}) ${DN_PROJECT_USER_HOME:?err}
+      chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_PROJECT_PATH:?err}
+      chown -R $(id -u ${DN_PROJECT_USER}):$(id -g ${DN_PROJECT_USER}) ${DN_DEV_WORKSPACE:?err}
+    } || {
+      # Collect debugg information on faillure
+      pwd
+      tree -agu
+      tree -agu ${DN_PROJECT_USER_HOME}
+      tree -agu ${DN_DEV_WORKSPACE}
+      exit 1
+    }
+
+    echo "Add project-develop aliases"
+    (
+      echo ""
+      echo "# >>> dockerized-norlab project-develop"
+      echo "# Dockerized-NorLab aliases (from project-develop img)"
+      echo "alias dn_info='source /dockerized-norlab/dockerized-norlab-images/container-tools/dn_info.bash'"
+      echo "alias dn_ros2_rebuild_dev_workspace='source /dockerized-norlab/project/project-develop/dn_ros2_rebuild_dev_workspace.bash'"
+      echo "alias dn_fetch_ros_env_variables='source /dockerized-norlab/project/project-develop/dn_fetch_ros_env_variables.bash'"
+      echo "alias dn_expose_container_env_variables='source /dockerized-norlab/project/project-develop/dn_expose_container_env_variables.bash'"
+      echo "# <<< dockerized-norlab project-develop"
+      echo ""
+    ) >> /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
 EOF
 
+# ....TMP DEV introspection........................................................................
+## (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
+#RUN <<EOF
+#    # TMP DEV introspection
+#    cat /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash
+#    echo -e "\n${0}: not implemented error\n" && exit 1
+#EOF
+# ........................................................................TMP DEV introspection....
 
-# (Priority) ToDo: Was moved in dn_project_core_init.bash. On task NMO-548 end >> delete next bloc ↓↓
-## (Priority) ToDo: Not sure its usefull to symlink those (ref task NMO-548)
-#RUN ln -s "${DN_DEV_WORKSPACE}" "${DN_PROJECT_USER_HOME}${DN_DEV_WORKSPACE}" && \
-#    ln -s "${DN_PROJECT_PATH}" "${DN_PROJECT_USER_HOME}${DN_PROJECT_PATH}"
+# ....TMP DEV dn_info.bash refactor................................................................
+## (CRITICAL) ToDo: on task end >> mute next bloc ↓↓
+WORKDIR /dockerized-norlab/dockerized-norlab-images/container-tools
+COPY --from=context-dn-container-tools ./dn_info.bash .
+# ................................................................TMP DEV dn_info.bash refactor....
 
-FROM project-specific-ros-setup AS test-ssh-user
+
+FROM dockerized-norlab-project-internal AS test-ssh-user
 USER "${DN_SSH_SERVER_USER}"
 SHELL ["/bin/bash", "-c"]
 WORKDIR /
 
-RUN test $(whoami) == "${DN_SSH_SERVER_USER}" && test -d /home/${DN_SSH_SERVER_USER} || exit 1
+RUN <<EOF
+    {
+        test $(whoami) == "${DN_SSH_SERVER_USER}" && \
+        test -d /home/${DN_SSH_SERVER_USER} ;
+    } || exit 1
 
-RUN echo "===Check that ROS source is available via the ssh daemon user====================" \
-    && printenv \
-    && echo "" \
-    && echo "AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'}" \
-    && python -c "import rclpy" \
-    && echo "" \
-    && echo "===ros2 install pkg sanity check=================================================" \
-    && { \
+    echo "===Check that ROS source is available via the ssh daemon user===================="
+    printenv
+    {
+      test -n "${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'}" && \
+      python -c "import rclpy" ;
+    } || exit 1
+
+    echo "===ros2 install pkg sanity check================================================="
+    {
         test -n "$(ros2 pkg list | grep -e ros_core)" &&  \
         test -n "$(ros2 pkg list | grep -e rclpy)" &&  \
         test -n "$(ros2 pkg list | grep -e ackermann_msgs)" &&  \
-        test -n "$(ros2 pkg list | grep -e vesc_msgs)" ; \
-    }||  exit 1
+        test -n "$(ros2 pkg list | grep -e vesc_msgs)" ;
+    } ||  exit 1
+EOF
 
-FROM project-specific-ros-setup AS test-project-user
+FROM dockerized-norlab-project-internal AS test-project-user
 USER ${DN_PROJECT_USER:?'Env variable needs to be set and non-empty.'}
 SHELL ["/bin/bash", "-c"]
 ARG TARGETPLATFORM
 ARG BUILDPLATFORM
 WORKDIR /
 
-RUN test $(whoami) == "${DN_PROJECT_USER}" && test -d /home/${DN_PROJECT_USER} || exit 1
+RUN <<EOF
+    {
+        test $(whoami) == "${DN_PROJECT_USER}" && \
+        test -d /home/${DN_PROJECT_USER} ;
+    } || exit 1
+EOF
 
-RUN echo "===Check that ROS source is available in DN_PROJECT_USER ssh daemon user=============" \
-    && printenv \
-    && echo "" \
-    && echo "AMENT_PREFIX_PATH=${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'}" \
-    && python -c "import rclpy" \
-    && echo "" \
-    && echo "===ros2 install pkg sanity check=================================================" \
-    && { \
+RUN <<EOF
+    echo "===Check that ROS source is available via the ssh daemon user===================="
+    printenv
+    {
+      test -n "${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'}" && \
+      python -c "import rclpy" ;
+    } || exit 1
+
+    echo "===ros2 install pkg sanity check================================================="
+    {
         test -n "$(ros2 pkg list | grep -e ros_core)" &&  \
         test -n "$(ros2 pkg list | grep -e rclpy)" &&  \
         test -n "$(ros2 pkg list | grep -e ackermann_msgs)" &&  \
-        test -n "$(ros2 pkg list | grep -e vesc_msgs)" ; \
+        test -n "$(ros2 pkg list | grep -e vesc_msgs)" ;
     } ||  exit 1
+EOF
 
 WORKDIR ${DN_PROJECT_USER_HOME}
-RUN { \
+RUN <<EOF
+    {
         test -x "${DN_PROJECT_USER_HOME}/dn_expose_container_env_variables.bash" && \
         bash dn_expose_container_env_variables.bash && \
         TMP_DOTENV_EXPOSE_PATH="/dn_container_env_variable/.env.dn_expose_${DN_CONTAINER_NAME}" && \
         test -f "${TMP_DOTENV_EXPOSE_PATH}" && \
         TMP_DOTENV_EXPOSE_USER_PATH="${DN_PROJECT_USER_HOME}/dn_container_env_variable/.env.dn_expose_${DN_CONTAINER_NAME}" && \
-        test -f "${TMP_DOTENV_EXPOSE_USER_PATH}" ; \
+        test -f "${TMP_DOTENV_EXPOSE_USER_PATH}" ;
     } || exit 1
 
-RUN { \
-        test -x "${DN_PROJECT_USER_HOME}/dn_ros2_rebuild_dev_workspace.bash" && \
-        if [[ ${TARGETPLATFORM:?err} != ${BUILDPLATFORM:?err} ]]; then \
-          bash ./dn_ros2_rebuild_dev_workspace.bash 'virtualization' ; \
-        else \
-          bash ./dn_ros2_rebuild_dev_workspace.bash 'native' ; \
-        fi ; \
+    test -x "${DN_PROJECT_USER_HOME}/dn_ros2_rebuild_dev_workspace.bash" || exit 1
+
+    if [[ ${TARGETPLATFORM:?err} != ${BUILDPLATFORM:?err} ]]; then
+      source ./dn_ros2_rebuild_dev_workspace.bash 'virtualization' || exit 1
+    else
+      source ./dn_ros2_rebuild_dev_workspace.bash 'native' || exit 1
+    fi
+
+    {
+        test -x "${DN_PROJECT_USER_HOME}/dn_entrypoint.init.bash" && \
+        test -x "${DN_PROJECT_USER_HOME}/dn_entrypoint.attach.bash" && \
+        test -d "${DN_PROJECT_USER_HOME}" && \
+        test -d "${DN_PROJECT_PATH}" && \
+        test -d "${DN_DEV_WORKSPACE}"&& \
+        test -d "${DN_PROJECT_USER_HOME}/$(basename ${DN_DEV_WORKSPACE})" && \
+        test -d "${DN_PROJECT_USER_HOME}/${DN_PROJECT_GIT_NAME}" ;
     } || exit 1
 
-RUN { \
-    test -x "${DN_PROJECT_USER_HOME}/dn_entrypoint.init.bash" && \
-    test -x "${DN_PROJECT_USER_HOME}/dn_entrypoint.attach.bash" && \
-    test -d "${DN_PROJECT_USER_HOME}" && \
-    test -d "${DN_PROJECT_PATH}" && \
-    test -d "${DN_DEV_WORKSPACE}" ; \
+    {
+        test -x "${DN_PROJECT_USER_HOME}/dn_fetch_ros_env_variables.bash" && \
+        source ./dn_fetch_ros_env_variables.bash ;
     } || exit 1
 
-
-RUN { \
-    test -x "${DN_PROJECT_USER_HOME}/dn_fetch_ros_env_variables.bash" && \
-    bash ./dn_fetch_ros_env_variables.bash ; \
+    echo "container-tools sanity check"
+    {
+        test -f /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bashrc.bash && \
+        test -f /dockerized-norlab/dockerized-norlab-images/container-tools/dn_bash_alias.bash && \
+        test -f /dockerized-norlab/dockerized-norlab-images/container-tools/dn_info.bash && \
+        source /dockerized-norlab/dockerized-norlab-images/container-tools/dn_info.bash ;
     } || exit 1
+EOF
 
 # unset entrypoint for running test stage
 ENTRYPOINT [ "" ]
 
-FROM project-specific-ros-setup AS final
+FROM dockerized-norlab-project-internal AS final
 
 USER ${DN_PROJECT_USER:?'Env variable needs to be set and non-empty.'}
 SHELL ["/bin/bash", "-c"]
