fix: refine Dockerized norlab build matrix setup and compatibility checks
- Improved compatibility checks for Ubuntu and ROS2 distros in Dockerfiles.
- Enhanced setup and error handling for ROS2 repository configurations.
- Added a new runtime script for opening a containerized Ubuntu 22.04 terminal.

Issue NMO-756

diff --git a/dockerized-norlab-images/core-images/base-images/l4t-images/Dockerfile.l4t.squash b/dockerized-norlab-images/core-images/base-images/l4t-images/Dockerfile.l4t.squash
--- a/dockerized-norlab-images/core-images/base-images/l4t-images/Dockerfile.l4t.squash
+++ b/dockerized-norlab-images/core-images/base-images/l4t-images/Dockerfile.l4t.squash
@@ -295,13 +295,19 @@ RUN echo -e "        TARGETPLATFORM: $(echo ${TARGETPLATFORM:?'Env var not set i
 
 # Note: see https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
 #       for docker buildx environment variables available inside the container: i.e. [TARGET|BUILD]PLATFORM
-RUN echo "Dockerized-NorLab build system › image for target device: ${TARGETPLATFORM:?'Buildx environment variables not available in container'}" \
-    && echo -e "DEV introspection\n\n \
-        Buildx env\n \
-          BUILDPLATFORM: ${BUILDPLATFORM}\n \
-          TARGETPLATFORM: ${TARGETPLATFORM}\n \
-        Real build target architecture: $(uname -m)\n" \
-    && if [[ "${TARGETPLATFORM}" =~ "linux/arm64".* ]] && [[ "$(uname --machine)" == "x86_64" ]]; then \
-          echo "[DN-build-system ERROR] Test stage architecture missmatch!" && exit 1 ; \
-       fi
+RUN <<EOF
+    n2st::print_msg "Ubuntu version is $( source /etc/lsb-release && echo ${DISTRIB_CODENAME})"
+
+    echo "Dockerized-NorLab build system › image for target device: ${TARGETPLATFORM:?'Buildx environment variables not available in container'}"
+    echo -e "DEV introspection\n
+    Buildx env
+      BUILDPLATFORM: ${BUILDPLATFORM}
+      TARGETPLATFORM: ${TARGETPLATFORM}
+    Real build target architecture: $(uname -m)\n"
+
+    if [[ "${TARGETPLATFORM}" =~ "linux/arm64".* ]] && [[ "$(uname --machine)" == "x86_64" ]]; then
+        echo "[DN-build-system ERROR] Test stage architecture missmatch!"
+        exit 1
+    fi
+EOF
 
