NMO-337 | Fix › refactor ros sourcing logic from "source /opt/ros/${ROS_DISTRO}/install/setup.bash" to "source /opt/ros/${ROS_DISTRO}/setup.bash"

diff --git a/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile b/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
--- a/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
+++ b/dockerized-norlab-images/core-images/dn-project/project-develop/Dockerfile
@@ -42,14 +42,8 @@ RUN touch /etc/profile.d/02-dn-source-ros-system-wide.sh \
       echo ""; \
       echo "# Dockerized-NorLab › Execute ros sourcing system wide instead of in .bashrc which is not executed"; \
       echo "# in non-interactive shell such as in pycharm-debugger"; \
-      echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/install/setup.bash\""; \
+      echo "echo \"sourcing /opt/ros/${ROS_DISTRO}/setup.bash\""; \
       echo "source /opt/ros/${ROS_DISTRO}/setup.bash"; \
-      echo ""; \
-      echo "echo \"ros2 install pkg sanity check\""; \
-      echo "[[ -n \"$(ros2 pkg list | grep -e ros_core)\" ]] || echo \"Can't find ros_core localy\" && exit "; \
-      echo "[[ -n \"$(ros2 pkg list | grep -e rclpy)\" ]] || echo \"Can't find rclpy localy\" && exit "; \
-      echo "[[ -n \"$(ros2 pkg list | grep -e ackermann_msgs)\" ]] || echo \"Can't find ackermann_msgs localy\" && exit "; \
-      echo "[[ -n \"$(ros2 pkg list | grep -e vesc_msgs)\" ]] || echo \"Can't find vesc_msgs localy\" && exit "; \
       echo ""; \
       echo "# Dockerized-NorLab › Quickhack for connecting to pycharm-debugger (over ssh)"; \
       echo "export DN_CONTAINER_NAME=$DN_CONTAINER_NAME"; \
@@ -101,7 +95,13 @@ RUN echo "Check that ROS source is available via the ssh daemon user" \
     && rosversion -d \
     && printenv \
     && echo ${AMENT_PREFIX_PATH:?'Build argument needs to be set and non-empty.'} \
-    && python -c "import rclpy"
+    && python -c "import rclpy" \
+    && echo "" \
+    && echo "ros2 install pkg sanity check" \
+    && $( [[ -n "$(ros2 pkg list | grep -e ros_core)" ]] || echo "Can't find ros_core localy" && exit 1 )  \
+    && $( [[ -n "$(ros2 pkg list | grep -e rclpy)" ]] || echo "Can't find rclpy localy" && exit 1 )  \
+    && $( [[ -n "$(ros2 pkg list | grep -e ackermann_msgs)" ]] || echo "Can't find ackermann_msgs localy" && exit 1 )  \
+    && $( [[ -n "$(ros2 pkg list | grep -e vesc_msgs)" ]] || echo "Can't find vesc_msgs localy" && exit 1 )
 
 ENTRYPOINT [ "" ]
 
